name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main, master]

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install -e .[dev]
          # Ensure latest resonate-sdk is installed for Python >=3.12 API surface
          pip install -U "resonate-sdk>=0"
      - name: Show Python and resonate-sdk version
        run: |
          python --version
          python -c "import resonate; from resonate import Resonate; import sys; print('resonate-sdk:', getattr(resonate,'__version__','unknown'), 'has_local:', hasattr(Resonate,'local'))"
      - name: Run unit tests with coverage
        run: |
          pytest -m unit -v \
            --cov=src \
            --cov-report=term-missing \
            --cov-report=json \
            --junit-xml=test-results.xml
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.sha }}
          path: |
            test-results.xml
            coverage.json
          retention-days: 7
